name: Day Trading

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  fetch:
    name: Update day traing report
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt install python3-full
          python3 -m venv virtual
          source virtual/bin/activate
          pip3 install pandas twstock lxml bs4
      - name: Checkout stock tool
        uses: actions/checkout@v4
        with:
          path: tool
      - name: Checkout db
        uses: actions/checkout@v4
        with:
          repository: xanthein/stock_db
          token: ${{ secrets.DAILY_REPORT_TOKEN }}
          path: stock_db
          lfs: true
      - name: Get day trading report
        run: |
          source virtual/bin/activate
          python3 tool/stock/get_report.py trading
      - name: Update db
        run: |
          source virtual/bin/activate
          python3 tool/stock/db.py add --trading-report=$(ls trading_*) stock_db/daily_report
      - name: commit db
        run: |
          if git -C stock_db status daily_report | grep -q modified;
          then
              echo "Update $(ls trading_*)"
              git config --global user.name 'Dirk Su'
              git config --global user.email 'xanthein@users.noreply.github.com'
              git -C stock_db commit -am "Update $(ls trading_*)"
              git -C stock_db push
          fi
